//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.IO;

namespace System
{
    internal class Xml
    {
        internal class Serialization
        {
            internal class XmlSchemaProviderAttribute : Attribute
            {
            }

            internal class XmlRootAttribute : Attribute
            {
            }
        }

        internal class Schema
        {
            internal class XmlSchema
            {
                internal void Write(MemoryStream s1)
                {
                    throw new NotImplementedException();
                }
            }

            internal class XmlSchemaAny
            {
            }
        }
    }
}